# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'blblpic.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtWidgets


class Ui_BiliBili(object):
    def setupUi(self, BiliBili):
        BiliBili.setObjectName("BiliBili")
        BiliBili.resize(400, 300)
        self.line = QtWidgets.QFrame(BiliBili)
        self.line.setGeometry(QtCore.QRect(0, 170, 401, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.progressBar = QtWidgets.QProgressBar(BiliBili)
        self.progressBar.setGeometry(QtCore.QRect(100, 200, 301, 21))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.label = QtWidgets.QLabel(BiliBili)
        self.label.setGeometry(QtCore.QRect(20, 180, 61, 51))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(BiliBili)
        self.label_2.setGeometry(QtCore.QRect(40, 20, 51, 31))
        self.label_2.setObjectName("label_2")
        self.label_4 = QtWidgets.QLabel(BiliBili)
        self.label_4.setGeometry(QtCore.QRect(30, 70, 71, 31))
        self.label_4.setObjectName("label_4")
        self.toolButton = QtWidgets.QToolButton(BiliBili)
        self.toolButton.setGeometry(QtCore.QRect(6, 120, 101, 31))
        self.toolButton.setObjectName("toolButton")
        self.pushButton = QtWidgets.QPushButton(BiliBili)
        self.pushButton.setGeometry(QtCore.QRect(150, 250, 93, 28))
        self.pushButton.setObjectName("pushButton")
        self.textEdit = QtWidgets.QTextEdit(BiliBili)
        self.textEdit.setGeometry(QtCore.QRect(140, 20, 221, 31))
        self.textEdit.setObjectName("textEdit")
        self.textEdit_2 = QtWidgets.QTextEdit(BiliBili)
        self.textEdit_2.setGeometry(QtCore.QRect(140, 70, 221, 31))
        self.textEdit_2.setObjectName("textEdit_2")
        self.textEdit_3 = QtWidgets.QTextEdit(BiliBili)
        self.textEdit_3.setGeometry(QtCore.QRect(140, 120, 221, 31))
        self.textEdit_3.setObjectName("textEdit_3")

        self.retranslateUi(BiliBili)
        QtCore.QMetaObject.connectSlotsByName(BiliBili)

    def retranslateUi(self, BiliBili):
        _translate = QtCore.QCoreApplication.translate
        BiliBili.setWindowTitle(_translate("BiliBili", "BiliBili画册"))
        self.label.setText(_translate("BiliBili", "下载进度"))
        self.label_2.setText(_translate("BiliBili", "画册ID"))
        self.label_4.setText(_translate("BiliBili", "图片名称"))
        self.toolButton.setText(_translate("BiliBili", "选择文件路径"))
        self.pushButton.setText(_translate("BiliBili", "开始!"))
